services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: "telemeter_nginx"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - influxdb
      - grafana
      - tornado
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_network

  influxdb:
    image: influxdb:2.6.1
    container_name: "telemeter_influxdb"
    platform: linux/x86_64
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - ui_network
      - db_network
      - nginx_network

  grafana:
    image: grafana/grafana:9.3.6
    container_name: "telemeter_grafana"
    platform: linux/x86_64
    environment:
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    ports:
      - 3000:3000
    env_file: ".env"
    depends_on:
      - influxdb
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/dashboard-settings:/etc/grafana/provisioning/dashboards"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    networks:
      - ui_network
      - nginx_network

  tornado:
    restart: always
    build: ./tornado
    container_name: "telemeter_tornado"
    ports:
      - 8888:8888
    platform: linux/x86_64
    volumes:
      - ./tornado:/app
    env_file: ".env"
    depends_on:
      - influxdb
    networks:
      - db_network
      - nginx_network

networks:
  db_network:
  ui_network:
  nginx_network:

volumes:
  influxdb_data:
  grafana_data:
