version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: tornado
    ports:
      - 8888:8888
    depends_on:
      - db

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: 'telemeter.fujiy.dev -> http://tornado:8888'
      STAGE: 'local'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
      WEBSOCKET: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  db-store:
  https-portal-data:
