services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: "telemeter_nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_network

  influxdb:
    image: influxdb:2.6.1
    container_name: "telemeter_influxdb"
    platform: linux/x86_64
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - ui_network
      - db_network
      - nginx_network

  grafana:
    image: grafana/grafana:9.3.6
    container_name: "telemeter_grafana"
    platform: linux/x86_64
    environment:
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ui_network
      - nginx_network

  tornado:
    restart: always
    build: ./tornado
    container_name: "telemeter_tornado"
    ports:
      - 8888:8888
    platform: linux/x86_64
    volumes:
      - ./tornado:/app
    env_file: "./tornado/.env"

    networks:
      - db_network
      - nginx_network

networks:
  db_network:
  ui_network:
  nginx_network:

volumes:
  influxdb_data:
  grafana_data:
