{
 "title": "rockoon_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Geo Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Geo Location",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for later use\r\n      tracker_latitude: float(v: r.latitude),  // Use explicit float conversion\r\n      tracker_longitude: float(v: r.longitude)\r\n    }))\r\n"
    },
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for alignment in union\r\n      mission_latitude: float(v: r.latitude),\r\n      mission_longitude: float(v: r.longitude)\r\n    }))"
    },
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for alignment in union\r\n      rocket_latitude: float(v: r.latitude),\r\n      rocket_longitude: float(v: r.longitude)\r\n    }))"
    },
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for alignment in union\r\n      ground_station_1_latitude: float(v: r.latitude),\r\n      ground_station_1_longitude: float(v: r.longitude)\r\n    }))"
    },
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for alignment in union\r\n      ground_station_2_latitude: float(v: r.latitude),\r\n      ground_station_2_longitude: float(v: r.longitude)\r\n    }))"
    },
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,  // Keep the timestamp for alignment in union\r\n      ground_station_3_latitude: float(v: r.latitude),\r\n      ground_station_3_longitude: float(v: r.longitude)\r\n    }))"
    }
   ]
  },
  {
   "title": "Tracker Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tracker Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      deg: int(v: r._value),  \r\n      min: int(v: (r._value - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      sec: (((r._value - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Tracker Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tracker Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      degrees: int(v: r._value),  \r\n      minutes: int(v: ((r._value) - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      seconds: ((((r._value) - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "MissionLatitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mission Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      degrees: int(v: r._value),  \r\n      minutes: int(v: ((r._value) - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      seconds: ((((r._value) - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Mission Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mission Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      degrees: int(v: r._value),  \r\n      minutes: int(v: ((r._value) - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      seconds: ((((r._value) - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Rocket Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rocket Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      degrees: int(v: r._value),  \r\n      minutes: int(v: ((r._value) - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      seconds: ((((r._value) - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Rocket Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rocket Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      \r\n      degrees: int(v: r._value),  \r\n      minutes: int(v: ((r._value) - float(v: int(v: r._value))) * 60.0),  // Extract minutes\r\n      seconds: ((((r._value) - float(v: int(v: r._value)))) * 60.0 % 1.0) * 60.0\r\n    }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Tracker Altitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure altitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mission Altitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure altitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rocket Altitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure altitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Geo Location",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n|> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: r.latitude),\r\n      longitude: float(v: r.longitude)\r\n    }))"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"pressure altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      TimeStamp: r._time,\r\n      pressure: r.pressure,\r\n      temperature: r.temperature,\r\n      altitude: r[\"pressure altitude\"]\r\n    }))"
    }
   ]
  },
  {
   "title": "Power",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
    }
   ]
  },
  { "title": "Mission ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Geo Location",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"gps altitude\"])\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"pressure altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      TimeStamp: r._time,\r\n      pressure: r.pressure,\r\n      temperature: r.temperature,\r\n      altitude: r[\"pressure altitude\"]\r\n    }))"
    }
   ]
  },
  {
   "title": "Environment (Mission specific)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tank pressure\" or r[\"_field\"] == \"thrust pressure\" or r[\"_field\"] == \"tank temperature\" or r[\"_field\"] == \"phi\" or r[\"_field\"] == \"theta\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      TimeStamp: r._time,\r\n      tank_pressure: r[\"tank pressure\"],\r\n      thrust_pressure: r[\"thrust pressure\"],\r\n      tank_temperature: r[\"tank temperature\"],\r\n      phi: r[\"phi\"],\r\n      theta: r[\"theta\"]\r\n    }))"
    }
   ]
  },
  {
   "title": "Power",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mission\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
    }
   ]
  },
  {
   "title": "Rocket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Location",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n|> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: r.latitude),\r\n      longitude: float(v: r.longitude)\r\n    }))"
      }
     ]
    },
    {
     "title": "Environment",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"pressure altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      TimeStamp: r._time,\r\n      pressure: r.pressure,\r\n      temperature: r.temperature,\r\n      altitude: r[\"pressure altitude\"]\r\n    }))"
      }
     ]
    },
    {
     "title": "Power",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rocket\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Ground Station 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Location",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n|> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: r.latitude),\r\n      longitude: float(v: r.longitude)\r\n    }))"
      }
     ]
    },
    {
     "title": "Power",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station1\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Ground Station 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Location",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n|> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: r.latitude),\r\n      longitude: float(v: r.longitude)\r\n    }))"
      }
     ]
    },
    {
     "title": "Power",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station2\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Ground Station 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Location",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"gps altitude\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    TimeStamp: r._time,\r\n    latitude: r.latitude,\r\n    longitude: r.longitude,\r\n    gpsaltitude: r[\"gps altitude\"]\r\n  }))\r\n|> map(fn: (r) => ({\r\n      r with\r\n      latitude: float(v: r.latitude),\r\n      longitude: float(v: r.longitude)\r\n    }))"
      }
     ]
    },
    {
     "title": "Power",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "query": "from(bucket: \"rockoon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ground station3\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    Backup_Volt: r[\"backup power voltage\"],\r\n    Primary_Volt: r[\"primary power voltage\"],\r\n    Primary_Current: r[\"primary power current\"],\r\n    Vdd_Volt: r[\"vdd voltage\"],\r\n    Vdd_current: r[\"vdd current\"],\r\n  }))\r\n  "
      }
     ]
    }
   ]
  }
 ]
}