apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    jsonData:
      version: Flux
      organization: wasa_rockoon
      defaultBucket: rockoon
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    editable: true
